name: 15-minute-cron
on:
  push:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl \
          --url 'https://fastmail-jkjustjoshing.vercel.app/api/mail' \
          --header 'Authorization: Basic ${{ secrets.AUTH_TOKEN }}'
